name: 定时任务集合

on:
  push:
    branches:
      - main
  schedule:
    # 任务C：每30分钟
    - cron: '*/1 * * * *'

    # 未来你可以继续加
    # 任务A：每1小时
    # - cron: '0 */1 * * *'
    # 任务B：每6小时
    # - cron: '0 */6 * * *'

jobs:
  # ======================================
  # 任务C：仅在 push 或 每30分钟定时 执行
  # ======================================
  test-cos:
    name: 检查COS是否合法
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' || contains(github.event.schedule, '*/30 * * * *')

    steps:
      - name: 运行脚本
        run: echo "${{ github.event.schedule }}----${{ github.event_name }}"
  # ======================================
  # 未来你加任务A（每1小时）就这样写
  # ======================================
  # task-a:
  #   runs-on: ubuntu-latest
  #   if: contains(github.event.schedule, '0 */1 * * *')
  #   steps:
  #     - run: echo "任务A 每1小时执行"

  # ======================================
  # 未来你加任务B（每6小时）就这样写
  # ======================================
  # task-b:
  #   runs-on: ubuntu-latest
  #   if: contains(github.event.schedule, '0 */6 * * *')
  #   steps:
  #     - run: echo "任务B 每6小时执行"